### ISSUE TITLE
Frame-busting has no opt-out

### ISSUE THREAD

**Issue by gozer** [mozilla-iam/auth0-deploy#117]
Since 5df201cde406216387ff37e4fc2ca1628fa4c9da landed, it's impossible to avoid the SSO pages from frame-busting themselves to the top.

In some case, it could be a desired feature. Feels like just unconditionally frame-busting to the top frame is somewhat of a heavy hammer.

Could this feature be somehow optionnal ?

**Comment by gdestuynder** [comment]
only the hosted lock is supported, non-hosted lock (ie modal) will eventually stop working
See also https://github.com/mozilla/iam-project-backlog/issues/40

If that is still a problem regardless or there is something else we did not foresee, please do re-open

thanks!

**Comment by gozer** [comment]
@gdestuynder I imagine that by "hosted lock" you mean the simple redirect to auth0 for authentication process, correct?

In my case, I filed this issue because I am building a dashboard using frames, all authenticated by auth0 with mod_auth_openidc. However, if one frame's content session expires and not the top document, the redirect to auth0 then proceeds to frame-bust out of there, breaking my UI, effectively.

I was just asking to see if there would be some solution/workaround that could help me here, thanks!

**Comment by tinnightcap** [comment]
@gdestuynder  If I understand correctly what you are saying, this has just destroyed weeks of our work, which we have done after consulting with the security team and getting approval for the current implementation. As we have finished the work, we will continue to use the existing method. If that requires whitelisting all Nubis accounts, that will need to happen that going forward. We simply do not have the time to re-implement the solution at this time.

I hope that this is simply me not understanding fully what you are describing here. I will put a meeting on the calendar for tomorrow so we can get a clearer understanding of the issue.

**Comment by gdestuynder** [comment]
@tinnightcap Do you have a link to the approval for the current implementation? Maybe that'll clear things up.

**Comment by gdestuynder** [comment]
@tinnightcap @gozer additionally is it possible to have the meeting at 8am PDT with @hmitsch ?

**Comment by tinnightcap** [comment]
@gdestuynder I moved the meeting up and added @hmitsch. I will look up the doc and have it on-hand before we meet.

Cheers

**Comment by gdestuynder** [comment]
thanks - we met this morning and the issue is with the logout functionality that sends the user-agent back to the RP's `redirect_uri` with a `returnto` (not sure about exact syntax) parameter. The parameter is passed over from the RP to the OP (Auth0) and back again - the RP then sends the user-agent to that return URL which is not the frameset of the RP.

Basically, it's a `mod_auth_openidc` behavior and we believe/hope this can be fixed on the RP / module side by changing or removing or filtering out that parameter.
