### ISSUE TITLE
Cannot start duo 2FA setup

### ISSUE THREAD

**Issue by MikkCZ** [mozilla-iam/auth0-deploy#162]
With the need of 2FA, I wanted to setup duo for my LDAP account. Unfortunately it does not allow me to do on https://login.mozilla.com/duo/. A note I am contributor. Here are the requests to [create](https://bugzilla.mozilla.org/show_bug.cgi?id=903558) and later [update](https://bugzilla.mozilla.org/show_bug.cgi?id=1237204) my LDAP, if that helps.

STR:
1. Visit https://login.mozilla.com/duo/.
2. Login with LDAP.
3. Click the Start setup button.
4. Nothing happens.

In the browser console, before clicking the button I see several CSP errors (for jquery and few more for a duo subdomain). For the same duo subdomain, there is also some 404 error printed. When clicking the button, another CSP error is shown. If it's safe to post the console content here or needed to send you, please let me know the best channel.

**Comment by MikkCZ** [comment]
CC @hmitsch @KaiRo-at

**Comment by hmitsch** [comment]
IAM Team internal conversation triggered at https://discourse.mozilla.org/t/volunteer-ldap-and-duo-mfa/21259/

(Sorry that this Discourse forum is limited to [IAM Project members](https://mozillians.org/group/iam-project/) only.)

**Comment by hmitsch** [comment]
Linking this to a thread in the [public IAM discussion forum](https://discourse.mozilla.org/t/mozillians-org-and-sso-login-issues/21104/).

**Comment by hmitsch** [comment]
Linking issue https://github.com/mozilla-iam/auth0-deploy/pull/146

**Comment by MikkCZ** [comment]
Thank you @hmitsch, unfortunatelly I am still facing the same problem there, including the errors shown in Firefox console.

**Comment by hmitsch** [comment]
@MikkCZ thank you ... investigating. :-)

**Comment by floatingatoll** [comment]
@MikkCZ, would you be willing to try again on a new (temporary) Firefox profile, so that we can rule out several categories of potential issues?

**Comment by MikkCZ** [comment]
I have tested with a fresh profile now and the errors are the same there.

**Comment by floatingatoll** [comment]
:( Thank you for trying it out.

**Comment by MikkCZ** [comment]
Seems I have found a workaround. The only think that does not work is the "Start setup" button because CSP blocks it from functioning in iframe on login.mozilla.com. Today I have got a weird idea to middle click that button to open the link in a new tab. Then I have been able to set 2FA for my account there.

**Comment by hmitsch** [comment]
@MikkCZ this is an amazing story. Happy to see that you were able to set up Duo MFA.

I will route the CSP error to the correct person in another ticket.

Best regards,
   Henrik

**Comment by hmitsch** [comment]
@MikkCZ did you happen to take a screenshot of the CSP error you saw?

**Comment by floatingatoll** [comment]
Or if your session is still open, Devtools Console might still have the CSP error.

Was the Start Setup button inside a Duo iframe? Or, was it prior to Duo?

**Comment by MikkCZ** [comment]
I haven't, but I still see some errors in the console:
```Content Security Policy: Nastavení stránky zablokovalo načítání zdroje na self („script-src https://login.mozilla.com https://mozorg.cdn.mozilla.net/en-US/tabzilla/tabzilla.js https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js“). Source: onfocusin attribute on DIV element.
Content Security Policy: Nastavení stránky zablokovalo načítání zdroje na self („default-src https://api-4b043da5.duosecurity.com“). Source: onfocusin attribute on DIV element.
Content Security Policy: Nastavení stránky zablokovalo načítání zdroje na self („default-src https://api-4b043da5.duosecurity.com“). Source: onfocusin attribute on DIV element.```

But maybe @KaiRo-at or @MekliCZ haven't set up DUO and can still reproduce?

**Comment by floatingatoll** [comment]
Interesting. Thank you! Thinking.

**Comment by april** [comment]
Usually this is caused by using the deprecated way of setting an event handler on an DOM node.

Assuming that `div` is the DOM node, this is wrong:

`div.onfocusin = function () {};`

Instead, use this:

`div.addEventListener("focusin", function() {});`

**Comment by rtucker-mozilla** [comment]
@MikkCZ Did you use some kind of duo security interface to add your device or the one inside of login.mozilla.com?

You should be able to simply click the bottom "Multi Factor Authentication" link which will take you to the management for MFA devices.

https://login.mozilla.com/duo/ is just an iframe from duo security that should not have the ability to manage devices.

**Comment by MekliCZ** [comment]
These are the errors:
`Content Security Policy: Nastavení stránky zablokovalo načítání zdroje na self („script-src https://login.mozilla.com https://mozorg.cdn.mozilla.net/en-US/tabzilla/tabzilla.js https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js“). Source: onfocusin attribute on DIV element.`
`Content Security Policy: Nastavení stránky zablokovalo načítání zdroje na self („default-src https://api-4b043da5.duosecurity.com“). Source: onfocusin attribute on DIV element.`
`Content Security Policy: Nastavení stránky zablokovalo načítání zdroje na https://api-4b043da5.duosecurity.com/frame/enroll/flow?sid=MjVkNGYyNzYwN2JjNDcyOWFlYmQ2NWEzZjM2ZWJkMmM%3D%7C193.86.64.162%7C1512404177%7C67375766ac4c6fdc711fa3111915ec63b277c98f („child-src https://api-4b043da5.duosecurity.com/frame/web/v1/auth“).`

The last one appears when I click the "Start setup" button.

**Comment by rtucker-mozilla** [comment]
The CSP errors are a red herring

**Comment by rtucker-mozilla** [comment]
It appears as though @MikkCZ never finished initially enrolling for MFA via the login.mozilla.com native device management interface.

The following screenshot shows the start setup button inside of the iframe from duo.

https://www.dropbox.com/s/6vznc6on6km248c/Screenshot%202017-12-04%2008.19.18.png?dl=0

I've made a code change to better ensure that the Multifactor Authentication link is always available to community members.

**Comment by rtucker-mozilla** [comment]
I've worked through different scenarios with @jdow and we've been able to replicate the issue.
It appears as though @MikkCZ never finished enrolling completely. Then when we came back to login.mozilla.com he guessed or was told to go to /duo/ which is where the confusion about the CSP headers and "Start Setup" button have came from.

I've made a code change to ensure the link for "Multifactor Authentication" is always visible which takes the user to our own device management page allowing for more devices than what is allowed for inside of the duo interface.

This device enrollment functionality seems new to me.

**Comment by MikkCZ** [comment]
> @MikkCZ Did you use some kind of duo security interface to add your device or the one inside of login.mozilla.com?

I have middle-clicked the "Start setup" button which opened the iframe in a standalone tab.

> You should be able to simply click the bottom "Multi Factor Authentication" link which will take you to the management for MFA devices.

When I go to https://login.mozilla.com/duo/ now, the iframe asks me to confirm via the app or SMS code and afterwards it redirects me to https://login.mozilla.com/ itself. There I can open https://login.mozilla.com/duo_enrollments/ with the device management.

> Then when we came back to login.mozilla.com he guessed or was told to go to /duo/ which is where the confusion about the CSP headers and "Start Setup" button have came from.

@hmitsch told me about it https://discourse.mozilla.org/t/mozillians-org-and-sso-login-issues/21104/3?u=mstanke

**Comment by floatingatoll** [comment]
(FWIW - Middle-clicking the "Start setup" button is not one of the
supported use cases, and very well could cause CSP problems and/or break
the entire registration workflow. Thanks for letting us know you tried
that!)

**Comment by gdestuynder** [comment]
My understanding of https://discourse.mozilla.org/t/mozillians-org-and-sso-login-issues/21104/3?u=mstanke is that this is fixed
Please reopen if that's not the case
