### ISSUE TITLE
Explore if we can obviate the NLX /connections call by testing for RP support of connection type in an Auth0 rule

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/auth0-deploy#187]
Explore if Auth0 rules run both 
* after Auth0 has authenticated the user
* before auth0 checks to see if the RP supports the connection type

If this is the case :

Create a rule which checks to see if the RP does not support the connection type that the user is using. This can be done by comparing the connection type passed in the query parameter to the `@@config@@` RP supported connection information

If that rule finds that the RP does *not* support the connection type, redirect the user back to NLX instead of letting the flow continue where Auth0 would deliver an error page on the `/authorize` endpoint because the RP doesn't support the connection type the user is using.

Once this is done, NLX can remove the `/connections` call during autologin and drastically speed up autologin as requested in mozilla-iam/auth0-custom-lock#97

**Comment by gene1wood** [comment]
It sounds like from what @gdestuynder reported from his test that our Auth0 rules run *after* Auth0 detects that the connection type isn't in the RP's list of supported connection types.

@gdestuynder Would you confirm and close this if that's the case?

**Comment by gdestuynder** [comment]
that's correct :(
