### ISSUE TITLE
Forbidden page asks to login with google, instead of FxA

### ISSUE THREAD

**Issue by viorelaioia** [mozilla-iam/auth0-deploy#188]
STR:
1. Have a mozillians account with passwordless, google and fxa identities (fxa is the login identity for this account).
2. Try to login passwordless

Expected:
Forbidden page asking the user to login with fxa is shown

Actual:
Forbidden page asking to login with google is shown 
"Sorry, you may not login using passwordless email. We require login to be performed using the most secure method available for your account, which is Google."

Account used: viorelaioia@gmail.com, token: https://pastebin.mozilla.org/9082711

**Comment by viorelaioia** [comment]
CC: @gdestuynder

**Comment by gdestuynder** [comment]
Thanks! see above 2 prs that should fix it
