### ISSUE TITLE
Users can login with both github and fxa identities

### ISSUE THREAD

**Issue by viorelaioia** [mozilla-iam/auth0-deploy#204]
After discussions on #participationsystems channel,  we figured out that there is an issue with the rule that makes fxa more secure than github and doesn't allow users to login with github after upgrading to fxa.

STR:
1. Login to github in mozillians
2. Navigate to settings page and upgrade to firefox accounts
3. Logout
4. Navigate to sso.mozilla.com
5. Login with github

Expected:
Forbidden error page shown, user is not able to login.

Actual:
User is able to login with github, even though fxa is most secure identity.

Note:
Group information exists only in fxa identity.
This seems to be related only to github - upgrade to fxa flow. 
If trying to login to mozillians again using github, error message asking to login with fxa is shown (from mozillians, not auth0 forbidden error page).

**Comment by viorelaioia** [comment]
CC: @gdestuynder , @andrewkrug

**Comment by gdestuynder** [comment]
@viorelaioia what is the user id? (could it be that the primary email does not match? the racheting is by primary email only)

**Comment by viorelaioia** [comment]
@gdestuynder , I'm using same email for both github and fxa identities (viorelaioia@gmail.com). 
From what I understood from office hours with @andrewkrug , the rule that sets fxa as more secure than github is not deployed in prod. 
This is how the hierarchy of the identities should be: https://github.com/mozilla-iam/auth0-deploy/blob/master/rules/force-users-login-most-secure-method.js#L49. 
And this is what we currently have in prod: 
<img width="758" alt="screen shot 2018-06-25 at 7 40 00 am" src="https://user-images.githubusercontent.com/5293100/41868363-8da82db2-78be-11e8-92b5-83b6d58e8d97.png">

**Comment by gdestuynder** [comment]
yes, thats odd

**Comment by gdestuynder** [comment]
https://gist.github.com/gdestuynder/351217b755da87f1e59cfe506c509845 is the diff to re-rollout

**Comment by gdestuynder** [comment]
adding this to tomorrow's change window

**Comment by viorelaioia** [comment]
This is fixed in prod. After upgrading from github to fxa, users are not able to login with github anymore, as fxa is most secure.
Closing the issue.
