### ISSUE TITLE
CIS-Claims-fixups change in live prod but not in repo

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/auth0-deploy#228]
There's an addition to the production deployed CIS-Claims-fixups.js as compared to what's in the repo in [this area](https://github.com/mozilla-iam/auth0-deploy/blob/master/rules/CIS-Claims-fixups.js#L137-L138)

The live code says
```
   function cb(new_groups) {
     user.app_metadata = user.app_metadata || {};
     if (new_groups !== undefined) {
       user.groups = new_groups;
       user.app_metadata.groups = new_groups;
```

which introduces the new line

`       user.groups = new_groups;`

Should this change be retained and captured in the repo? What is the purpose of this change?

**Comment by gdestuynder** [comment]
what would only make a difference if groups are not reintegrated from metadata to the main group structure by auth0, which they should
that said since its in prod and ive seen this behavior change before im porting it back to dev

thx!
