### ISSUE TITLE
Ratcheting bypass for Common Voice on Production

### ISSUE THREAD

**Issue by Gregoor** [mozilla-iam/auth0-deploy#231]
It'd be great if ratcheting could be bypassed for Common Voice on Production, [as it was done before on Dev](https://github.com/mozilla-iam/auth0-deploy/pull/213).

We're using auth.mozilla.auth0.com for Common Voice and our auth0 client ids are:
`t6K0dg86KPvhkIgFAFz1CyC6reG8UV21`
and
`YwL6bJ8mXFiCplWbMLaX2fqu715rKP8u`

**Comment by gdestuynder** [comment]
its done
