### ISSUE TITLE
Cannot login to any testrp in dev 

### ISSUE THREAD

**Issue by viorelaioia** [mozilla-iam/auth0-deploy#248]
**STR:** 
1. Navigate to https://testrp.security.allizom.org/
2. Click the Sign In button for one of the RPs on the page (e.g: "Nginx+Lua with Social, LDAP and Passwordless options")
3. Enter your LDAP credentials and click "Enter" button

**Expected:**
Duo page is displayed

**Actual:**
Message saying user was logged out from the RP is returned

**Note:** 
Login is not working for the other login methods either (github, google, fxa). 
It also doesnt't work on Mozillians staging and sso staging RPs.

![screenshot from 2019-01-07 10-45-38](https://user-images.githubusercontent.com/5293100/50758115-e71fd580-1269-11e9-806d-bf19c2695acf.png)

**Comment by gdestuynder** [comment]
there was a stray test rule which i removed
