### ISSUE TITLE
No linking when logging in with Github (non-mfa or mfa) + FxA (mfa) accounts

### ISSUE THREAD

**Issue by rleitan** [mozilla-iam/auth0-deploy#251]
[Prerequisites]:
Github (non mfa), FxA (mfa)
Autologin disabled
No previous login in IAM

[Steps to reproduce]:
1. Open a new Firefox profile
2. Navigate to Mozillians staging
3. Log in with Github, create the account, then log out
3. Log in with FxA

[Expected result]:
Account linking should occur, user_id should be github's user id

[Actual result]:
Postman shows two different identities: e.g.  user_id: oauth2|firefoxaccounts|xxxx and user_id:github|xxxxx

Account linking(as a user_id for the two identities(Github and Firefox Accounts) is done only after logging again with the less secure ( e.g. Github)

[Note]:
The issue is reproducible also with Github (mfa) + FxA (mfa)

**Comment by gdestuynder** [comment]
hi, unfortunately did not get time for this today and will recheck tomorrow

**Comment by gdestuynder** [comment]
I believe this comes from this fix https://github.com/mozilla-iam/auth0-deploy/commit/935d7542a6377f87e4d5b5525321c82067d0e9f5 which introduced new bad behavior in this case (should be `=> 1` identities (i.e. target has 1 or more linked identities)

**Comment by gdestuynder** [comment]
Fix was ported in https://github.com/mozilla-iam/auth0-deploy/pull/255#pullrequestreview-202920867

**Comment by rleitan** [comment]
I confirm it's fixed!
