### ISSUE TITLE
When lock renders, passwordless button displays early then is hidden then revealed

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/auth0-deploy#29]

**Comment by jeffbryner** [comment]
FWIW: this has something to do with the customizeLock function. It shows while the loading css object is present, then takes it's place afterwards. 

If I remove the passwordless.. the same behavior happens with the ldap button, so seems to be a timing thing.

**Comment by jeffbryner** [comment]
Here's a snippet using the MutationObserver to catch the appearance of the auth0-lock-submit class and using it to trigger: 

` <script>
  
    // set up an observer to watch for auth0 nodes to trigger our customizations
    // since not all auth0 lock states emit events when ready/seen, etc. 
    // select a broad target node
    var target = document.getElementById('widget-container');
     
    // create an observer instance to watch all subtree modifications
    var observer = new MutationObserver(function(mutations) {
      mutations.forEach(function(mutation) {
        if (mutation.type == 'childList' && mutation.addedNodes.length > 0) {
            //console.log(mutation.addedNodes)
            mutation.addedNodes.forEach(function(node){
              if (node.className=="auth0-lock-submit") {
                customizeLock();
                //customizeSubmitButton();
                customizeLDAPFields();     
              }
            })
        }
      });    
    });
     
    // configuration of the observer:
    var config = { attributes: true, childList: true, characterData: true , subtree: true};
     
    // pass in the target node, as well as the observer options
    observer.observe(target, config);
    
    var APPS_WITH_TOS = [['phonebook-dev', 'https://www.mozilla.org/en-US/privacy/']];`

if I uncomment the customizeSubmitButton() call, I end up with duplicate login with email and login with ldap buttons for some reason.. probably jquery doing some favors and creating things that don't exist rather than modifying them due to timing?

**Comment by gene1wood** [comment]
PR #54 swaps out the method by which we wait for elements to show up in the lock. It replaces the [window.requestAnimationFrame()](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame) method with the newer [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver).

I've put together PR #72 which also solves this problem but continues to use `requestAnimationFrame` which maintains support for IE 10 (which we'd lose with `MutationObserver`)

I'd recommend we go with this alternative that keeps browser support more broad.
