### ISSUE TITLE
How to request scopes that return only `openid` and `email` without profile data

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/auth0-deploy#301]
This issue stems from #269 

How can we request the scopes of `openid` and `email` and get only those claims. We need this for the AWS federated CLI. Currently the logic in #269 causes any scope request other than `openid` to send along custom claims.

Can we change the logic to send custom claims when a user requests `profile` scope?

**Comment by gdestuynder** [comment]
"yes" :)

I'd just extend that logic to include `email`, or maybe, inverse it and only include the additional claims if:
- at least one claim starts with `https://..`
- the `profile` claim is requested
 and otherwise wipe "extra claims that weren't part of the request"
