### ISSUE TITLE
Remove PR approval for master branch.

### ISSUE THREAD

**Issue by rtucker-mozilla** [mozilla-iam/auth0-deploy#372]
I propose removing the approval step for merging into master.
It can be time prohibitive.

**Comment by rtucker-mozilla** [comment]
@sciurus ACK please
@gcoxmoz ACK Please

**Comment by sciurus** [comment]
Since the flow is master == dev, ACK.

**Comment by gcoxmoz** [comment]
Cautious ACK.  I worry about this being hard to get back to (if we need to), but I don't want to deny it at this point.

**Comment by gene1wood** [comment]
Enabling a single actor to make changes to auth0-deploy has the security impact of losing dual sign off and changes to auth0-deploy give full access to everything at Mozilla. Is there an improvement to the process that would accomplish the same thing? For example, explicitly stating both who the community of reviewers are and an SLA for getting reviews done?

**Comment by rtucker-mozilla** [comment]
The change is simple enough to implement should we ever want to. I think another thing might be to make this repo private anyway. I can't imagine why anyone outside of mozilla should have access to or care about it. Perhaps another issue to track that decision.

I'm remove the approval for PR into master.

**Comment by gene1wood** [comment]
> I think another thing might be to make this repo private anyway

I think the benefits we get of increased security rigour with working in the public out weigh the benefits and added potential risk of non public data sneaking in to the code base were it private.
