### ISSUE TITLE
Cache GitHub username in Auth0

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/auth0-deploy#401]
In the [new GitHub enterprise integration](https://github.com/mozilla-iam/auth0-deploy/blob/master/rules/GHE-Groups.js), in order to reduce traffic to the PersonAPI, increase speed of login and prevent a CIS outage or network latency from preventing users from being able to login to GitHub, I'd recommend caching the discovered GitHub username in [each user's `app_metadata`](https://auth0.com/docs/users/metadata)

A person's GitHub username is unlikely to change frequently and as a result if you cache the value fetched from the PersonAPI in the user's `app_metadata`, for most logins no call to PersonAPI need be made. You could pick a cache expiration time (say once a day or once a week) and user's would have a better experience (as opposed to being blocked on the PersonAPI call with each authentication to GitHub Enterprise.

When caching the GitHub Username, store the username and the datetime that it was fetched (to make cache expiration decisions)

**Comment by floatingatoll** [comment]
I have objections to this proposal, which I've presented in #iam for consideration.

**Comment by floatingatoll** [comment]
Based on last week's discussion, I don't think anyone will be accepting this issue as described right now, so I'm going to close this.
