### ISSUE TITLE
Putting an invalid email address in the passwordless field causes error message on login with LDAP

### ISSUE THREAD

**Issue by tristanweir** [mozilla-iam/auth0-deploy#46]
Go into a Lock 
Click Log In With Email
Put in some text (not a full, properly formatted e-mail address) 
Click Back
Click log in with LDAP
Put in LDAP creds
Try to click Log In. The CSS highlights the login button but no action takes place

Note that if you don't include a complete e-mail address in the LDAP e-mail field, clicking Login does give you a popup telling you to put in a valid e-mail address. So some logic is taking place. It just isn't completing the log in

**Comment by tristanweir** [comment]
Chrome only. Works in Firefox

**Comment by gene1wood** [comment]
Turns out this isn't related to browser. The cause is the invalid email address in the passwordless field. Clicking submit triggers an error popup about the email.
