### ISSUE TITLE
Missing scheme reference on pages/login.html:189

### ISSUE THREAD

**Issue by claudijd** [mozilla-iam/auth0-deploy#50]
Was doing a light code review and noticed that pages/login.html does not specify a scheme.

     <script src="//cdnjs.cloudflare.com/ajax/libs/ie8/0.2.5/ie8.js"></script>

This content is available over HTTP and HTTPS, so I think we should be more explicit about that.

**Comment by marumari** [comment]
While it should be more explicit, this format will match the scheme of the current page.  (just fyi)
