### ISSUE TITLE
Lock remembers LDAP session when logging back in with passwordless

### ISSUE THREAD

**Issue by gdestuynder** [mozilla-iam/auth0-deploy#52]
Steps:
- Login to https://social-ldap-pwless.testrp.security.allizom.org/ with an LDAP login
- Logout (https://social-ldap-pwless.testrp.security.allizom.org/logout) from testrp
- Login again to https://social-ldap-pwless.testrp.security.allizom.org/ but with passwordless
=> you are immediately logged in (even thus you also get an email, there is no need to click on the link)
=> you are logged in as the LDAP user instead of the passwordless user

This seems to be because there is a browser side cookie that is sent to auth0 during the login transaction, and that behaves like a "remember last login" (even thus this option is off in our lock)

This is both a UX and security issue since the users would not expect the auth0 session to be remembered (which it should not)

**Comment by gene1wood** [comment]
I'm hoping fixing #39 will solve this.

**Comment by gdestuynder** [comment]
did not fix it
it appears it may be related to something stored by auth0 that correspond to the cookie id, rather than the cookie itself

**Comment by tristanweir** [comment]
Unable to reproduce outside kang's specific machine/instance. Possibly Firefox Nightly release bug

**Comment by gdestuynder** [comment]
This has been found externally, so I looked at it again and finally found the issue. Its detailed here, including how to reproduce: https://bugzilla.mozilla.org/show_bug.cgi?id=1319450

Proposed fix:
ensure the lock never sends both a call to passwordless API *and* usernamepassword API (either by changing the code flow or emptying the LDAP login fields)

**Comment by tristanweir** [comment]
Similar to #46 , except in that case you have incorrect data in the Passwordless field that is causing an unseen error to be generated.

**Comment by gene1wood** [comment]
This bug is also manifested in this report https://bugzilla.mozilla.org/show_bug.cgi?id=1319822

**Comment by gene1wood** [comment]
My fix for this in PR #70 solves this but does not solve #46 as #46 though similar isn't affected.

**Comment by gene1wood** [comment]
This fixes the issue when clicking `send email` but not when hitting the <kbd>Enter</kbd> key.
