### ISSUE TITLE
Odd action description on login after previously logging in and out with a GitHub identity

### ISSUE THREAD

**Issue by claudijd** [mozilla-iam/auth0-deploy#53]
During testing, I observed what I believe to be some slightly off wording in the lock.  Here's how to reproduce...

1.) Login with GitHub account
2.) Logout
3.) Revisit login screen and get this screen
<img width="315" alt="screen shot 2016-11-16 at 4 47 39 pm" src="https://cloud.githubusercontent.com/assets/794283/20367343/0e94b668-ac1d-11e6-84ef-6814d92c240c.png">

What I find bizarre about this is that as a user, I know this is my account, but really what I think this link should say is something to the effect of "use a different identity to login".  Otherwise, an end user who's really literal/pedantic could end up in the state where they could file a support case because this is their account, but they just want to switch identity providers for this application.

**Comment by claudijd** [comment]
@gene1wood r?

**Comment by claudijd** [comment]
Additionally, I searched the code for this and couldn't find a reference to "Not your account" I wonder if it's is coming from auth0 logic.

**Comment by gdestuynder** [comment]
Defined at https://github.com/auth0/lock/blob/master/src/i18n/en.js#L63

**Comment by claudijd** [comment]
@gdestuynder thanks, I'll just send them a PR for it and state my case.

**Comment by tristanweir** [comment]
Propose "Use a different account"

**Comment by claudijd** [comment]
@tristanweir will do

**Comment by gene1wood** [comment]
@claudijd ya, this is a good thing to note. Thanks for opening auth0/lock#727 . I'll close this issue as it'll likely be addressed in the upstream issue

**Comment by tristanweir** [comment]
From #https://github.com/auth0/lock/pull/727
"You can easily override this using the languageDictionary attribute. You can also generate your own translation file, it should be a jsonp like this one https://cdn.auth0.com/js/lock/10.6.1/en.js
and you need to add it right after the lock one so the language is registered by the time you initialize lock. Once you do that, you can require this language using the language attribute (it should match with the name you put to the first parameter in the jsonp)."
