### ISSUE TITLE
LDAP connection doesn't return `email_verified` claim

### ISSUE THREAD

**Issue by LeoMcA** [mozilla-iam/auth0-deploy#60]
I noticed this when trying to create a new account on Discourse using LDAP, and Discourse wanted to send a verification email. It didn't want to do the same when using the passwordless connection.

If I log the information returned from `/userinfo` I see the problem, the passwordless connection returns a `email_verified` claim set to `true`, whereas the LDAP connection returns no `email_verified` claim.

Presuming we want RPs to treat emails returned from LDAP login as verified, the `email_verified` claim should be returned, set to `true`.

**Comment by tristanweir** [comment]
Resolved and config updated in puppet
