### ISSUE TITLE
Cannot login to mozillians.dev, neither passwordless, nor with LDAP 

### ISSUE THREAD

**Issue by viorelaioia** [mozilla-iam/auth0-deploy#96]
**Steps to reproduce:**
1. Navigate to https://mozillians-dev.allizom.org 
3. Click Sign in button on homepage;
4. Select the option to log in with email (passwordless);
5. Enter a valid email address and click Send Email button;
6. Click the login link from the email received.

**Expected:**
User is successfully logged in. 

**Actual:**
User is not logged in, homepage is shown. 

**Notes:**
1. If trying to login with LDAP, the user is redirected to homepage, after entering credentials.
2. Issue is only happening in dev. 
3. This issue is causing failures in automation, all tests that require login are failing when run on dev.

**Comment by viorelaioia** [comment]
CC: @tristanweir , @jdow , @hmitsch

**Comment by tristanweir** [comment]
Resolved. Furthermore https://mozillians-dev.allizom.org now points to production Auth0
