### ISSUE TITLE
Use new branding

### ISSUE THREAD

**Issue by jeffbryner** [mozilla-iam/auth0-deploy#97]
To help folks identify this as an official mozilla IDP, update the graphics to the new branding either via image or the upcoming font.

**Comment by gene1wood** [comment]
I've asked Tim Murray for guidance on finding the new brand font,logo,colors as everything I can find on the web and mana is the old brand.

**Comment by supnah** [comment]
Everything that is currently available can be found here:
http://designlanguage.mozilla.org/

Specific questions can be sent to ask-brand@mozilla.com

The fonts are not quite available yet, but coming soon. The colors are
still being finalized and will change from what's on that site.

Guidance is to use the black and white logo unless there is a very very
good reason to use a different version.

If you want to receive updates when new brand assets become available you
can sign up for this list: https://mail.mozilla.org/listinfo/brand-updates

**Comment by gene1wood** [comment]
Sounds good, I'll sign up on the mailing list to find out when we can get access to vector logo data (in the form of the font) so I can rebrand our lock. Thanks @supnah

**Comment by gdestuynder** [comment]
Updated social login branding for github in https://github.com/organizations/mozilla/settings/applications
